site_name: BoilerSync CLI
site_description: BoilerSync CLI documentation
repo_url: https://github.com/montaguegabe/boilersync
theme:
  name: mkdocs
nav:
  - Home: index.md
  - Ensemble Guide: ensemble.md
  - Template Metadata: template-metadata.md
  - Project Metadata: project-metadata.md
